env:
  - CGO_ENABLED=0
  - GOPROXY=https://goproxy.cn,direct
  - GO111MODULE=on
  - DOCKER_ORG=xiaoxuan6

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - .env
      - data/*
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
  groups:
    - title: '🚀 Features'
      regexp: 'feat:'
    - title: '🐛 Bug Fixes'
      regexp: 'fix:'
    - title: '🔨 Others'

dockers:
  - image_templates:
      - ghcr.io/{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Tag }}
      - ghcr.io/{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:latest
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.created={{ .Now.Format "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.url=https://github.com/xiaoxuan6/bookmarks
      - --label=org.opencontainers.image.title={{ .ProjectName }}
    extra_files:
      - .env
      - data
